[build]
  command = "npm install"
  publish = "."

[functions]
  directory = "functions"
  included_files = [
    "controladores/**",
    "data/categorias.json",
    "data/favoritos.json",
    "data/livros.json",
    "servicos/**",
    "./helterbooks-firebase-adminsdk-5stdg-fbbd1c5fbf.json"
  ]
